version: '3.8'
services:
  client-backend:
    image: bot_docker
    depends_on:
      - service-db
    network_mode: "host"

  service-db:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped