version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - service-db
    network_mode: "host"

  service-db:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped